// Code generated by "stringer -type=DomainType -trimprefix=DomainType"; DO NOT EDIT.

package device

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DomainTypeUnknown-0]
	_ = x[DomainTypeLight-1]
	_ = x[DomainTypeSwitch-2]
	_ = x[DomainTypeSensor-3]
}

const _DomainType_name = "UnknownLightSwitchSensor"

var _DomainType_index = [...]uint8{0, 7, 12, 18, 24}

func (i DomainType) String() string {
	if i < 0 || i >= DomainType(len(_DomainType_index)-1) {
		return "DomainType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DomainType_name[_DomainType_index[i]:_DomainType_index[i+1]]
}
