// Code generated by jsonenums -type=DomainType; DO NOT EDIT.

package device

import (
	"encoding/json"
	"fmt"
)

var (
	_DomainTypeNameToValue = map[string]DomainType{
		"DomainTypeUnknown": DomainTypeUnknown,
		"DomainTypeLight":   DomainTypeLight,
		"DomainTypeSwitch":  DomainTypeSwitch,
		"DomainTypeSensor":  DomainTypeSensor,
	}

	_DomainTypeValueToName = map[DomainType]string{
		DomainTypeUnknown: "DomainTypeUnknown",
		DomainTypeLight:   "DomainTypeLight",
		DomainTypeSwitch:  "DomainTypeSwitch",
		DomainTypeSensor:  "DomainTypeSensor",
	}
)

func init() {
	var v DomainType
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_DomainTypeNameToValue = map[string]DomainType{
			interface{}(DomainTypeUnknown).(fmt.Stringer).String(): DomainTypeUnknown,
			interface{}(DomainTypeLight).(fmt.Stringer).String():   DomainTypeLight,
			interface{}(DomainTypeSwitch).(fmt.Stringer).String():  DomainTypeSwitch,
			interface{}(DomainTypeSensor).(fmt.Stringer).String():  DomainTypeSensor,
		}
	}
}

// MarshalJSON is generated so DomainType satisfies json.Marshaler.
func (r DomainType) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _DomainTypeValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid DomainType: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so DomainType satisfies json.Unmarshaler.
func (r *DomainType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DomainType should be a string, got %s", data)
	}
	v, ok := _DomainTypeNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid DomainType %q", s)
	}
	*r = v
	return nil
}
